### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'mathcolor')     at Object.mathmlBuilder$6 [as font] 

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#17]
Using 0.10.5, I get the error below.  This did not occur on a previous recent version.

I am running this on a very large source document, so I am not sure of the particular place it first occurs.

```
TypeError: Cannot read properties of undefined (reading 'mathcolor')
    at Object.mathmlBuilder$6 [as font] (/Users/me/Documents/_Coding/Lecture_Notes/node_modules/temml/dist/temml.cjs:4906:28)
    at buildGroup$1 (/Users/me/Documents/_Coding/Lecture_Notes/node_modules/temml/dist/temml.cjs:2059:52)
    at buildExpression (/Users/me/Documents/_Coding/Lecture_Notes/node_modules/temml/dist/temml.cjs:2027:19)
    at buildExpressionRow (/Users/me/Documents/_Coding/Lecture_Notes/node_modules/temml/dist/temml.cjs:2045:18)
    at Object.mathmlBuilder [as ordgroup] (/Users/me/Documents/_Coding/Lecture_Notes/node_modules/temml/dist/temml.cjs:6701:12)
    at buildGroup$1 (/Users/me/Documents/_Coding/Lecture_Notes/node_modules/temml/dist/temml.cjs:2059:52)
    at Object.mathmlBuilder [as supsub] (/Users/me/Documents/_Coding/Lecture_Notes/node_modules/temml/dist/temml.cjs:7203:21)
    at buildGroup$1 (/Users/me/Documents/_Coding/Lecture_Notes/node_modules/temml/dist/temml.cjs:2059:52)
    at buildExpression (/Users/me/Documents/_Coding/Lecture_Notes/node_modules/temml/dist/temml.cjs:2027:19)
    at buildExpressionRow (/Users/me/Documents/_Coding/Lecture_Notes/node_modules/temml/dist/temml.cjs:2045:18)
```

Additionally, it seems that subscripts and superscripts with `\textcolor` does not produce what is expected (on the demo on the temml website) because it splits the text for one element per character, see [here](https://temml.org/#x%5E%7B%5Ctextcolor%7Bred%7D%7Bhello%7D%7D%0A%5C%5C%0Ax_%7B%5Ctextcolor%7Bred%7D%7Bhello%7D%7D).

---

From a code comment on 0.10.5:
>In LaTeX, color is not supposed to change the spacing of any node.
>So instead of wrapping the group in an <mstyle>, we apply the color individually to each node and return a document fragment

I had noticed, too, that wrapping an operator in a color sometimes produces incorrect spacing, such as `\textcolor{red}{+}`, which I now cannot reproduce on the temml website, so I am hopeful that the the code change will fix this, and appreciate the fix for that.

**Comment by ronkok** [comment]
@universemaster Thank you for alerting me. Both of the issues you have identified are now resolved in release 0.10.6.
